#!/bin/bash

# Print usage
usage() {
	echo "Usage:"
	echo "    $(basename $0) [-h|-?] [-n FILE_NAME] [-ericqf] SITE_CODE"
	echo ""
	echo "Options:"
	echo "    -h/-?"
	echo "        Displays the help/usage message. AKA... this..."
	echo "    -n FILE_NAME"
	echo "        Specifies a different file lcoation for the connection list."
	echo "        The default file location is the same directory as the script."
	echo "    -e"
	echo "        Puts the script into edit mode. Edit mode allows you to change"
	echo "        the properties of that connection. If a field is left blank then"
	echo "        the current value is kept. If the value is blank you will be"
	echo "        prompted every time you select that site to enter a value."
	echo "        Will create a backup of connections as a .backup "
	echo "    -r"
	echo "        Logs in as root. Also works with -c"
	echo "    -i"
	echo "        Returns only the IP of the provided site and exits"
	echo "    -c"
	echo "        Returns the username@ip formated for use with scp."
	echo "          ie. \"scp \$(site -c SITE_CODE):file1 .\""
	echo "    -q"
	echo "        Quite. Makes the script have minimal output."
	echo "    -d"
	echo "        Delete. Deletes the entry. Will create a backup of connections as a .backup"
	echo "    -f"
	echo "        Force. Forces the script so it does not ask for confirmation."
	echo "    -p"
	echo "        Supply the program password (One password to rule them all)"
	echo "        This is not a site specifiv password. It is used to decrypt the other passwords"
	echo "    NOTE: The password can never be changed as it is used to encrypt the passwords of"
	echo "          each site. If the script's password changes it requires all site passwors to"
	echo "          be removed and re-entered. Also the passwords md5sum is hard coded."
	echo ""
	echo "Brought to you by Tyler Hoyt."
}

# Process Arguments
# A POSIX variable
OPTIND=1         # Reset in case getopts has been used previously in the shell.
EXPECT_ARG_COUNT=1 # number of args AFTER the flags
# Initialize our own variables:
DELIM=';'
ROOTUSER='root'
CONNECTIONS="$(dirname $(readlink -f $0))/connections"
EDIT=0
ROOT=0
IPONLY=0
USERIP=0
VERB=1
FORCE=0
DEL=0
PASSWORD=""	########################################### To make this program secure. remove the text between the quotes so it assigns PASSWORD an empty string.
HPASSWORD="1f23be7d7b7b36403c46be71939012a3  -" ############### This is the md5 of the password. 

while getopts "h?n:ericqfdp:" opt; do
    case "$opt" in
    h|\?)
        usage
		exit 0
        ;;
    n)
		CONNECTIONS=$(readlink -f $OPTARG)
		;;
	e)
		EDIT=1
		;;
	r)
		ROOT=1
		;;
	i)
		IPONLY=1
		;;
	c)
		USERIP=1
		;;
	q)
		VERB=0
		;;
	f)
		FORCE=1
		;;
	d)
		DEL=1
		;;
    p)
		PASSWORD=$OPTARG
		;;
	*)
        echo "What the hell did you enter???"
        exit 1
		;;
    esac
done

shift $((OPTIND-1))

[ "$1" = "--" ] && shift

if [ "$#" -ne "$EXPECT_ARG_COUNT" ]; then
	exit 0
fi

################################################################################
############################## Actual code... ##################################
################################################################################

ask() {
	#If force is turned on then don't ask, simply return true
	if [ "$FORCE" == "1" ] ; then
		return 0
	fi
	#Keep asking the question until I get a good response
	while :; do
		read -p "$1 (y/n): " -r
		echo
		case $REPLY in
			N|n)
		    	return 1
		    	;;
			Y|y)
		    	return 0
	    		;;
			*)
				echo "I dont understand \"$REPLY\""
				;;
		esac
	done
}

# If the user did not supply the password through the command line
#	and the password is not included in the headder then get it.
tries=0
while [ -z "$PASSWORD"  ] ; do
	read -sp "Password: " PASSWORD
	echo
	if [ "$(echo $PASSWORD | md5sum)" != "$HPASSWORD" ] ; then
		tries=$(($tries+1))
		echo "$tries failed attempt(s)"
		if [ $tries -eq 2 ] ; then
			echo "Hint: It's the same password used EVERYWHERE at Toptech"
		fi
		if [ $tries -eq 3 ] ; then
			echo "Too many failed attempts"
			exit 0
		fi
		PASSWORD=""
	fi
done

# Get the line that matchest the site code provided
line=$(grep "^$1" $CONNECTIONS)

# Ensure there is only one entry for that site code
if [ $(echo "$line" | wc -l) -gt "1" ]; then
	echo "There are two lines! ERROR, ERROR, DANGER WILL ROBINSON, DANGER!"
	return 1
fi

# If the line is good then parse it in to components
code=$(echo "$line" | cut -f1 -d$DELIM | sed "s/^\s\+//" | sed "s/\s\+$//")
ip=$(echo "$line" | cut -f2 -d$DELIM  | sed "s/^\s\+//" | sed "s/\s\+$//")
user=$(echo "$line" | cut -f3 -d$DELIM  | sed "s/^\s\+//" | sed "s/\s\+$//")
pass=$(echo "$line" | cut -f4 -d$DELIM  | sed "s/^\s\+//" | sed "s/\s\+$//")
rpass=$(echo "$line" | cut -f5 -d$DELIM  | sed "s/^\s\+//" | sed "s/\s\+$//")

#If the user wants the username@ip then print it for root or regular
if [ "$USERIP" == "1" ] ; then
	if [ "$ROOT" == "1" ] ; then
		echo "$ROOTUSER@$ip"
	else
		echo "$user@$ip"
	fi
	exit 0
fi

#If the user only wants the IP then print it and exit
if [ "$IPONLY" == "1" ] ; then
	echo "$ip"
	exit 0
fi

if [ "$DEL" == "1" ] ; then
	if ask "Do you want to delete $code?" ; then
		if ask "Are you sure you want to delete $code?" ; then
			sed -i.backup "/^$code.*/d" $CONNECTIONS
		fi
	fi
	exit 0
fi

#If anything is missing or we are in edit mode then prompt the user
if [ -z "$code" ]; then
	if ! ask "There is no site information for site \"$1\". Would you like to add it?"; then
		exit 0;
	fi
	mod=1
	code="$1"
fi

if [ -z "$ip" ] || [ "$EDIT" == "1" ] ; then
	echo "Enter new IP for site $code"
	read -p "Please enter an IP: " newip
	if [ ! -z "$newip" ] ; then
		ip=$newip
		mod=1
	fi
fi

if [ -z "$user" ] || [ "$EDIT" == "1" ] ; then
	echo "Enter new user information for site $code"
	read -p "Please enter the User Name: " newuser
	if [ ! -z $newuser ] ; then
		user=$newuser
		mod=1
	fi
fi

if [ -z "$pass" ] || [ "$EDIT" == "1" ] ; then
	newpass1="1"
	newpass2="2"
	while [ "$newpass1" != "$newpass2" ] ; do
    	read -sp "Enter new password for user $user at site $code: " newpass1
		echo
    	read -sp "Please re-enter the user's password: " newpass2
		echo
	done
	if [ ! -z $newpass1 ] ; then
		pass=$(echo $newpass1 | openssl enc -aes-128-cbc -a -salt -pass pass:"$PASSWORD")
		mod=1
	fi
fi

if [ -z "$rpass" ] || [ "$EDIT" == "1" ] ; then
	newrpass1="1"
	newrpass2="2"
	while [ "$newrpass1" != "$newrpass2" ] ; do
		read -sp "Enter new root password for site $code: " newrpass1
		echo
    	read -sp "Please re-enter the root password: " newrpass2
		echo
	done
	if [ ! -z $newrpass1 ] ; then
		rpass=$(echo $newrpass1 | openssl enc -aes-128-cbc -a -salt -pass pass:"$PASSWORD")
		mod=1
	fi
fi

# If any of the fields were modefied then ask if it's ok and write it to the file
if [ "$mod" == "1" ] ; then
	newstring="$code$DELIM $ip$DELIM $user$DELIM $pass$DELIM $rpass"
	echo -e "Writing connection to file:\n\t$newstring"
	if ask "Is this ok?" ; then
		sed -i.backup "/^$code.*/d" $CONNECTIONS
		echo "$newstring" >> $CONNECTIONS
	fi
fi

#Display the info for the user if verbose
if [ "$VERB" == "1" ] ; then 
	echo "Site Code:  $code"
	echo "IP:         $ip"
	echo "User:       $user"
	echo "user's pw:  $pass"
	echo "root pw:    $rpass"
fi

#Log in to site
if ! ask "Would you like to log in?"; then
	exit 0
fi
if [ "$ROOT" == "1" ] ; then
	$(dirname $(readlink -f $0))/sign_in $ip $ROOTUSER $(echo $rpass | openssl enc -aes-128-cbc -a -d -salt -pass pass:"$PASSWORD")
else
	$(dirname $(readlink -f $0))/sign_in $ip $user $(echo $pass | openssl enc -aes-128-cbc -a -d -salt -pass pass:"$PASSWORD")
fi
