#!/bin/bash

# This will take two arguments. the first being a file with the list of RPMs that need to be downloaded
# separated by a newline. the second is which website repo to get them form. (linuxbuild, linuxbuild5, 
# release, ect...)

cat $1 | while read line
do
    wget -r -l 50 --no-directories --accept "$(echo "$line" | sed -e 's/-/\*/g')" $2
done
